### ISSUE TITLE
Issues with themes in shared component library

### ISSUE THREAD

**Issue by janmonschke** [seek-oss/treat#113]
Hey all 👋 

I am currently setting up treat in a shared component library and am facing a couple of issues and hope you can help 💪 

My shared libraries use `useStyles` to resolve the styles depending on the theme that is used in a project. For some reason, the styles are not resolved when the components are used in projects.

I have created a test case repository here with a detailed problem description: [janmonschke/treat-testcase](https://github.com/janmonschke/treat-testcase)

My setup is as follows:

The components live [in this project](https://github.com/janmonschke/treat-testcase/tree/master/TheComponents):
```
TheComponents
  - Box
  - SimpleText
```

`Box` is a simpler version of [Braid's Box component](https://github.com/seek-oss/braid-design-system/blob/master/lib/components/Box/Box.tsx) and `SimpleText` just renders text in the current theme's `primary` color.

They are then required from [this project](https://github.com/janmonschke/treat-testcase/tree/master/TheProject):
```
TheProject
  - dependencies: TheComponents
```

When running `TheProject`, I noticed that the theme styles are not applied to the external components. They are only applied to the internal ones.

green | red
--- | ---
<img width="252" alt="greentheme" src="https://user-images.githubusercontent.com/68591/80714048-aa2dc100-8af4-11ea-933d-580c09f95582.png"> | <img width="248" alt="redtheme" src="https://user-images.githubusercontent.com/68591/80714061-ad28b180-8af4-11ea-8c76-da3e1e5d9c23.png">

The injected styles only show the theme classes that come from the project's `TextComponent`:

<img width="503" alt="injected" src="https://user-images.githubusercontent.com/68591/80714054-ab5eee00-8af4-11ea-921f-4c2f3e2a294d.png">

I'm wondering why they are not included. Is there something wrong with how I'm bundling `TheComponents`?

**Comment by maraisr** [comment]
Are you building the shared component library, and shipping that to npm?

In order for treat to work for both internal and external components, the `createTheme` files that i assume are in your component library - need to be available as "source" or at the very least not have been through webpack.

---

Side note; themes are resolved by discovering all `createTheme` function calls in all the `.treat` files. As these are compiled away, in your external project if these don't exist, there will be no theme.

**Comment by janmonschke** [comment]
Thanks for your answer @maraisr 👏 

> Are you building the shared component library, and shipping that to npm?
Yes, that is what I'm doing right now.

> themes are resolved by discovering all createTheme function calls in all the .treat files. As these are compiled away, in your external project if these don't exist, there will be no theme.

I was assuming sth like that. The theme files in this case are all in the project that is consuming the shared components. The components themselves do have some `.treat` files that are as simple as:

```
import { style } from "treat";

export const text = style((theme) => ({ color: theme.primary }));
```

If I understand you correctly: I would need to compile the `.treat` files in my component without the `treat/webpack` plugin? That way they can be discovered by the `treat/webpack` plugin in the consuming application?

**Comment by maraisr** [comment]
That is correct, but you can't just bundle with webpack without the treat/webpack-plugin because the filenames are important. And not just that, even if you were to use a cache-group to emit each .treat file as a .treat file, it'll be wrapped in webpacks' jsonp stuff, so then treat's compiler can't discover things.

What I have done, and exactly what Braid has done is to simply publish raw source code to npm, and add this node_modules path to the includes array of webpack.

Will also once again note; seeing as you've got consumer side theme usages also; you can't use `resolveClassName` manually.

**Comment by janmonschke** [comment]
Thanks again for you help 🙏 

>  (...) it'll be wrapped in webpacks' jsonp stuff, so then treat's compiler can't discover things.

True that does not seem like a good idea ;) 

> What I have done, and exactly what Braid has done is to simply publish raw source code to npm (...)

I see, I see. I wonder if that is possible in my case where we might have different versions of TypeScript in our projects. How are you dealing with other assets (svgs etc) in that case?

> Will also once again note; seeing as you've got consumer side theme usages also; you can't use resolveClassName manually.

Can you elaborate on that a bit more?
