### ISSUE TITLE
More clarity on where to apply pseudos

### ISSUE THREAD

**Issue by maraisr** [seek-oss/treat#117]
In the [docs](https://seek-oss.github.io/treat/data-types#styles) it states that `:hover` etc can be applied on the style object directly, and everything else on the selectors object. This has left some fragmentation in our team, where some have applied this in selectors under `&:hover`, rather than on the style object itself. 

Wondering if there could be more clarity around how this was intended to be used? Or if treat _could_ be more strict around where you can use `&:hover`, perhaps if its as basic as this, it could error much like how it errors now if you use sibling operators.

This I dare say could also be solved with a eslint rule.

**Comment by mattcompiles** [comment]
In the docs we mention "simple pseudos". That concept comes from [csstype](https://github.com/frenic/csstype#pseudo-types). Treat honours the contract they create. It's probably worth calling out that library in the docs for clarity. 

From a convention perspective it's really up to the project what they prefer to use, however, the type definitions should catch incorrect cases.

**Comment by maraisr** [comment]
That's true, however treat chose to expose "SimplePseudos" on the main style object here https://github.com/seek-oss/treat/blob/1fd5f1f2077fc79c1fd893d176034d85c8e75566/packages/treat/src/types.ts#L21 

Which I mean is okay, its just meant that you can define a thing in 2 places. And I get that yeah, it is up to the project to decide. 

Because treat chose to expose them on the root style object, it'd just be nice for treat to also try and say what they the prefer in systems. Like if its for DX reasons, then mention that.

This all originated when a fellow developer asked me where to put hover states, because the docs didn't specify.
