### ISSUE TITLE
Possibly incorrect extraction of `content` property on pseudo elements.

### ISSUE THREAD

**Issue by sean0x42** [seek-oss/treat#119]
So I found a little oddity when working with pseudo elements `::before` and `::after` combined with the `content` property. Using `content` is pretty niche as far as I've seen, but definitely has its uses. So if for example I had the following in treat:

```typescript
export const element = style(theme => ({
  color: theme.primary,
  '::after': {
    'content': 'test',
  }
}))
```

The output CSS would look like this (which is actually invalid)...

```css
.[some-selector]::after {
  content: test;
}
```

...when I would expect it to look like this:

```css
.[some-selector]::after {
  content: "test";
}
```

Now I get that this may just be an edge case of expected functionality, and that you should probably write the following instead. But in which case, maybe that should be documented somewhere?

```typescript
export const element = style(theme => ({
  color: theme.primary,
  '::after': {
    'content': '"test"',
  }
}))
```

Either way, thanks for the great library! Just thought I'd start a discussion.

**Comment by maraisr** [comment]
I can confirm that this is actually the case. We [actually do have a similar workaround](https://github.com/autoguru-au/overdrive/blob/302405b7a31d610146f3c3fbc895a5c062945cc5/lib/components/Alert/Alert.treat.ts#L21).

Basically the solution is to, as you've done. `content: "'test'"`

**Comment by mattcompiles** [comment]
Hey Mate 👋

This one has come up a bit from our own usage as well. The reason this is an issue is because the `content` property allows you to input quite a few different formats, some of which don't require quotes, hence why double quotes are required. 

What I think we can improve here is validate this property specifically and give a human readable message to explain what needs to be done.

**Comment by sean0x42** [comment]
Hi!

Yes I completely agree. I looked into `content` a bit more, and you're right: there are so many ways of using that property: <https://developer.mozilla.org/en-US/docs/Web/CSS/content>

If you look at the [formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/content#Formal_syntax) it's even scarier! Even just validating that property would be no easy task, unless we just cover the case of string vs. not string. I can totally understand why treat handles it in the way that it does presently.
