### ISSUE TITLE
Keyframes generating invalid name

### ISSUE THREAD

**Issue by barabrian** [seek-oss/treat#121]
### Subject of the issue
In some cases keyframes are generating names with invalid characters like '+'

### Your environment
* "treat": "1.4.1"

### Steps to reproduce
My case:
```js
'@keyframes': {
  to: {
    transform: 'translateX(100%)'
  },
}
```

### Expected behaviour
Generated names will follow the [custom-ident](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident) css data type

[from mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name)
> A name identifying the animation. This identifier is composed of a combination of case-sensitive letters a to z, numbers 0 to 9, underscores (_), and/or dashes (-). The first non-dash character must be a letter. Also, two dashes are forbidden at the beginning of the identifier. Furthermore, the identifier can't be none, unset, initial, or inherit.

### Actual behaviour
In some cases name will generate invalid characters
ex: _(image from chrome devtools, based on "Steps to reproduce")_
![image](https://user-images.githubusercontent.com/5655741/84646242-53881500-aef1-11ea-9e22-19a8a3477acd.png)

BTW. Thanks for a great library! 😀

**Comment by maraisr** [comment]
Great spot mate :100: thanks for this. I have raised a PR to fix this, hopefully the seek folk accept it.

Not sure if my fix is 100% as its a super blanket fix, but I think it'll iron out the issue you've described.

**Comment by Blastoplex** [comment]
Hey there! Were currently looking to implement treat in our design system and this issue has come up for us too.  Trying to migrate our [Skeleton](https://feelix.myob.com/#/Components/Layout/Skeleton) component form Styled components to Treat.

**Comment by Blastoplex** [comment]
Thanks @mattcompiles!
