### ISSUE TITLE
Does Treat support @support keyword? 

### ISSUE THREAD

**Issue by leahhou** [seek-oss/treat#131]
We are looking to write some styles for older browsers, specifically IE11. Thank you for your help!

**Comment by DavidBachmann** [comment]
It **currently does not** support that.
I've been wanting to give back to this project so I'm gonna try my hand at this and send a PR.

I'm thinking the syntax would be:

```js
export const myStyle = style({
  '@supports': {
    '(display: grid)': {
      display: 'grid',
    },
    'not (display: grid)': {
      display: 'flex',
    },
  },
})
```

**Comment by leahhou** [comment]
Cool, Thank is great! Keep up updated if it is released.

**Comment by informa** [comment]
That's great @DavidBachmann , as seems like globalStyle doesn't work either, where `${spinner.svg}` is a treat style.
```
globalStyle(`@supports (stroke-dasharray: 1, 150) ${spinner.svg}`, {
  display: 'block',
});
```
outputs something like, where it is invalid css as should have extra `{ }` around the .Spinner class.
```
@supports (stroke-dasharray:1,150) .Spinner-svg_l9nxT{display:none} 
```

**Comment by Blastoplex** [comment]
Similar to the above: 
Is there room in treat to add some kind of string > css with treat class interpolation. This would unblock loads of css feature gaps like the subject of this thread. 

```js
export const style = css(`
@supports (display: grid) {
  ${spinner.svg} {
    display: grid
  }
}
`)
```
or
```js
export const style = css((theme)=>(`
@supports (display: grid) {
  ${spinner.svg} {
    margin: theme.gutter
  }
}
`))
```
