### ISSUE TITLE
Usage with CSS `prefers-color-scheme`?

### ISSUE THREAD

**Issue by sean0x42** [seek-oss/treat#135]
Hey,

Just wondering if anyone has found a way to combine the CSS [`prefers-color-scheme` media selector](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) with treat? It would be great to define a dark and a light theme, and automagically swap between the two, but I can see how that could be difficult.

Thanks!

**Comment by maraisr** [comment]
This is all just "off the top of my head code", but think it'll work.

```tsx
import darkTheme from './darkTheme.treat';
import lightTheme from './lightTheme.treat';

const darkMode = window.matchMedia('(prefers-color-scheme: dark)');
const lightMode = window.matchMedia('(prefers-color-scheme: light)');

const ThemeProvider = ({ children }) => {
	const [theme, setTheme] = useState(() => {
		return darkMode.matches
			? darkTheme
			: lightMode.matches
				? lightTheme
				: darkTheme; // Default;
	});

	useEffect(() => {
		const changeToLight = (e) => {
			if (e.matches) {
				setTheme(lightTheme);
			} else {
				setTheme(darkTheme);
			}
		};
		const changeToDark = (e) => {
			if (e.matches) {
				setTheme(darkTheme);
			} else {
				setTheme(lightTheme);
			}
		};

		darkMode.addEventListener('change', changeToDark);
		lightMode.addEventListener('change', changeToLight);

		return () => {
			darkMode.removeEventListener('change', changeToDark);
			lightMode.removeEventListener('change', changeToLight);
		};
	}, []);

	return (<TreatThemeProvider theme={theme}>
		{children}
	</TreatThemeProvider>);
};
```

granted you can probably write a better way to swatch between them, but the premise is simple. You have 2 themes, just "activate" them when they should be.

One major downside is, you'll be eagerly loading the css that powers both themes. So you probably want to invest in some sort of lazy loading of those themes—or split your css another way. But that is a bundler question, not so much treat.

**Comment by sean0x42** [comment]
Awesome, thanks so much for the quick response and great example @maraisr! TIL about `window.matchMedia` and adding event listeners to media queries 🤔 That's some really useful stuff.

I will close this issue off since it's been answered perfectly! Thank you again
