### ISSUE TITLE
Can styleMap be made optional?

### ISSUE THREAD

**Issue by tom-sherman** [seek-oss/treat#142]
From my testing, the following two exports behave the same way.

```javascript
export const foo = styleMap({
  sm: {/* some styles */},
  lg: {/* some styles */}
})

export const foo = {
  sm: style({/* some styles */}),
  lg: style({/* some styles */})
}
```

However, if one of those styles is themed, it missing from the CSS output:

```javascript
export const foo = {
  sm: style({/* some styles */}),
  lg: style(theme => ({/* some styles */}))
}
```

I'm currently in the process of porting treat to ReScript as I think it can be a great solution to CSS in that ecosystem. Using styleMap makes a ReScript API much more convoluted to work with and implement.

**Comment by mattcompiles** [comment]
Hey Bud. 

Not sure what you mean by optional? The 2nd code example you posted looks fine to me, if it's not working it could be a bug. 

Also, to be clear the `styleMap` API can do things the `style` API can not. Mostly for when you want to generate a map of styles from your theme. 


```js
import mapValues from 'lodash/mapValues';

interface Theme {
	colors: Record<'red' | 'blue | 'yellow', string>;
}

const backgrounds = styleMap((theme: Theme) => mapValues(theme.colors, (color) => ({ backgroundColor: color })));
```

**Comment by tom-sherman** [comment]
@mattcompiles Thanks for the quick response. I chose optional because I thought this was expected behaviour, I was proposing that both of the examples should be a valid style declaration.

> The 2nd code example you posted looks fine to me, if it's not working it could be a bug.

Ok, I'll close this ticket and open a new one that specifies the bug.

> Also, to be clear the styleMap API can do things the style API can not. Mostly for when you want to generate a map of styles from your theme.

Yup I get that this is an ergonomics thing, the problem is in my use case `styleMap` is very difficult (read: impossible) to correctly type. I just want to use `{ a: style(theme => ...) }` for now.

**Comment by phil-lgr** [comment]
Same thoughs for me

![image](https://user-images.githubusercontent.com/9644867/108012137-9fd2aa00-6fd6-11eb-9774-b1d1321a13a8.png)

this is much easier to use in VSCode because CMD + Click correctly resolves and navigate to the class
