### ISSUE TITLE
Missing CSS in output when exporting an object with themed styles as values

### ISSUE THREAD

**Issue by tom-sherman** [seek-oss/treat#143]
I originally raised this as a feature request in #142, but @mattcompiles pointed out that this is probably a bug.

In the following treat file, `sm` exists in the CSS output but `lg` does not.

```javascript
// Example.treat.js
export const foo = {
  sm: style({/* some styles */}),
  lg: style(theme => ({/* some styles */}))
}
```

**Comment by mattcompiles** [comment]
If you're using themed styles you need to have created at least one theme as well. e.g. `createTheme({})`. Does that resolve the issue?

If so, then this issue is probably more about having a clear error be presented.

**Comment by tom-sherman** [comment]
That definitely fixes the failing test in the attached PR, haven't got it working in my project yet though. I'll keep trying and get back to you.
