### ISSUE TITLE
Webpack plugin broken in Next.js v10.0.6

### ISSUE THREAD

**Issue by wyattanderson** [seek-oss/treat#155]
I think this is an issue with Next.js itself, at least to the extent that the interaction of Next.js, plugins, and Webpack needs to be standardized. Creating an issue here anyway for the sake of linking to vercel/next.js#21721 (which includes details and reproduction steps) and hopefully saving some poor soul the time and effort of investigating this issue again.

**Comment by maraisr** [comment]
Can concur had same issue, "SingleEntryDepedency" error right? Or something to that effect? All I know was the error was misleading in that yes there is only one webpack. 10.0.5 works I believe.
