### ISSUE TITLE
Missing TS definition after upgrading to v2.0

### ISSUE THREAD

**Issue by kompot** [seek-oss/treat#158]
Hi,
tried to upgrade to v2.0 and TS definition imports seem to be broken.

Looks like something might gone wrong with the build as file `node_modules/treat/dist/treat.cjs.d.ts` contains the only line `export * from "./declarations/src/index";` and there's no `./declarations/src/index` relative to `dist` folder or anywhere else.

UPD
running `yarn run build` locacally in `treat` repo I see that there are lots of declaration files present `packages/treat/dist/declarations/src`

**Comment by zhongliangwang** [comment]
yeah same issue here. couldn't find `declaration` folder in `node_modules/treat/dist`

**Comment by mattcompiles** [comment]
Will look into this asap. On leave ATM.

**Comment by maraisr** [comment]
yeah this is an issue; 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/599459/108005659-ff679e80-7044-11eb-9428-6a6fea2fa278.png">
