### ISSUE TITLE
Don't set _createTheme_ to null when `window` is defined

### ISSUE THREAD

**Issue by maraisr** [seek-oss/treat#165]
When running unit tests in a jest environment, where "window" _could_ be defined—don't rip out the exports. Believe this to be a regression that was failed to be referenced in the v2 release.

**Comment by maraisr** [comment]
This fixes it for us https://github.com/autoguru-au/overdrive/commit/c58eb8b53d777bb43909b1b1e0b32a308620391b

**Comment by loliver** [comment]
Same issue in our environment, patching in `cjs.dev.js` was enough to get tests working, assuming `cjs.prod.js` wouldn't be needed in this instance.

**Comment by mattcompiles** [comment]
This is done to ensure style code doesn't accidentally leak into browser bundles. Our new build tool `preconstruct` creates browser bundles by checking the code for static `typeof window` checks. Unfortunately it doesn't remove the checks in the normal bundle. Might need a different strategy. 🤔

**Comment by loliver** [comment]
Are you able to release an alpha/beta/rc or something that doesn't have the window checks? I'm doing Webpack 5 upgrade testing at the moment with Storybook `6.2.0` going in to beta and would be great to be able to keep going with that next week. I'd fork and publish myself but have tried and failed to configure preconstruct to do what I want enough this week, haha.
