### ISSUE TITLE
Missing CHANGELOG for v2.0.x

### ISSUE THREAD

**Issue by andreipfeiffer** [seek-oss/treat#171]
I see that version `2.0` is released, but there is no Changelog entry.
Is there a place where I can find some documentation regarding what's changed in **`2.0.x`** since **`1.6.x`**?

Since it's a major version update, I guess there are some breaking changes.

Thank you!

**Comment by mattcompiles** [comment]
Hey Bud, We switched release strategies when we went to version 2. The changelogs for each package are now only located locally to each package. Should probably remove the top level one. The main treat release changelog can be seen here. https://github.com/seek-oss/treat/blob/master/packages/treat/CHANGELOG.md
