### ISSUE TITLE
How to use it with vite

### ISSUE THREAD

**Issue by jd-0001** [seek-oss/treat#183]
How can we use treat with [vite](https://vitejs.dev/)

If you can add/provide a guide for usage with vite it will be great.

Also, will it be able to extract CSS if I use vite? (If you can provide an example then it will be great)

Regards.

**Comment by markdalgleish** [comment]
treat's implementation is tightly coupled to webpack, but [vanilla-extract](https://vanilla-extract.style) (the successor to treat) doesn't have this limitation and has a first-class Vite integration, so we definitely recommend migrating.
