### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by amir-zahedi** [seek-oss/treat#186]
Love treat and how it's solving styling web apps but wondering if the project is still alive on the back burner or totally abandoned by seek? Would be great to have some advice from the team.
Cheers

**Comment by maraisr** [comment]
treat has been largely abandoned yes. In favour of their new vanilla-extract library.

You can find some helpful PR's on their braid project on a migration. 

---

I know we/I put a bet on Seek with treat at AutoGuru. And sadly yes, was a flop. Luckily the authoring of styles doesn't change much at all. So could be largely a find-replace job. (Without buying into their new atomic styling approach, sprinkles).

Main moment "no more useStyles" — can just use them from the import 🕺🏼

**Comment by amir-zahedi** [comment]
Thanks @maraisr for the clarification. I hope the Authors place a deprecated message on this project.

**Comment by maraisr** [comment]
They probably will eventually. But braid and subsequently seek still support a Frankenstein build supporting both. I dare say Braids now 100% VE but still need to support seek internals which may be treat. 

So think it's been abandoned but not necessarily broken.

**Comment by 72636c** [comment]
Sorry for leaving this so long! Yep, we've moved on to Vanilla Extract. A deprecation message has been added to the package and README.
