### ISSUE TITLE
Any chance to make it work with CRA?

### ISSUE THREAD

**Issue by stereobooster** [seek-oss/treat#42]
Hi. Thank you for the project. 

This question is asked in every zero-runtime library out there. Can we make it work with CRA out of the box, without need to eject? Can we make use of babel macros for example?

I kind of know the answer already (the problem is inside webpack API) but I keep hoping for the best. This is not an issue more of a discussion.

**Comment by montogeek** [comment]
It shouldn't be a problem using any CRA rewired library.

**Comment by mattsjones** [comment]
It shouldn't be difficult to integrate `treat` into CRA. It works in a very similar way to CSS modules and already has an idiomatic file extension (`.treat.js|ts`). It's mostly just a matter of adding the webpack plugin to your config. 

This issue is more one for the CRA maintainers though and whether they want to support `treat`.

**Comment by stereobooster** [comment]
<img width="601" alt="Screenshot 2019-07-27 at 10 34 49" src="https://user-images.githubusercontent.com/179534/61992114-3688f000-b05a-11e9-88ef-fa7fa7075dcc.png">

**Comment by danielberndt** [comment]
For reference, this is the code that's necessary to use treat in a CRA project via `react-app-rewired`

```js
// config-overrides.js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const TreatPlugin = require("treat/webpack-plugin");

module.exports = function override(config, env) {
  const isEnvDevelopment = env === "development";
  config.plugins.push(
    new TreatPlugin({
      outputLoaders: [
        isEnvDevelopment ? require.resolve("style-loader") : MiniCssExtractPlugin.loader,
      ],
    })
  );

  return config;
};
```
