### ISSUE TITLE
File layout doesn't seem to play nice with Next.js

### ISSUE THREAD

**Issue by wyattanderson** [seek-oss/treat#48]
Howdy! First off, thanks for this project. So far, it's been a pleasure to use. Getting it set up with [Next.js](https://nextjs.org) was generally painless:

```
const TreatPlugin = require('treat/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  webpack: (config, {isServer}) => {
    config.plugins.push(
      new TreatPlugin({
        outputLoaders: [MiniCssExtractPlugin.loader],
        outputCSS: !isServer,
      }),
      new MiniCssExtractPlugin()
    );

    return config;
  },
};
```

I've run into a tricky situation though, where Next.js barfs when building the site for production due to its opinionated approach to file storage. In a simple Next.js app, you'd have `pages/index.js` as the index page for your application. The corresponding Treat file for this would be, presumably, `pages/index.treat.js`. This works fine in development, but when building for production (when Next.js tries to determine the layout of your application for routing or whatever), you run into this error:

```
> Build error occurred
Error: automatic static optimization failed: found page without a React Component as default export in
pages/index.treat

See https://err.sh/zeit/next.js/page-without-valid-component for more info.
```

Bummer. Things I've tried to fix this:
- `export default () = > null` in my `pages/index.treat.js` file to shut up the error: no dice, Treat complains (probably rightly) that I'm exporting a `function`.
- Try to change the Next.js `pageExtensions` configuration option to somehow exclude `.treat.js` files: no dice, there's no Next.js configuration option for excluding files this way. Maybe there needs to be one. I don't think this would be a problem for corresponding `pages/index.css` or `pages/index.scss` files, though.
- Save the treat file for `pages/index.js` in `styles/index.treat.js`. Works, but doesn't feel great having the treat files in a separate directory.
- My current workaround: setting `TreatPlugin.test` to `/.treat.jsx$/`, setting Next.js's `pageExtensions` to `['js']`, and naming my treat files `.treat.jsx`. This works, but feels like a hacky workaround. It at least lets me keep my treat files in the same directory, though.

Anywho, I'm not totally certain what the right fix is. I'm not super familiar with Next.js, nor am I extremely experienced with Treat so far, so I thought I'd raise the issue and see what thoughts folks had. My gut tells me that adding a configuration option to Next.js to ignore files matching a certain pattern might be the right approach.

**Comment by mattsjones** [comment]
Hey 👋 

Glad you got it working with `next` so easily. Was wondering if it'd integrate well or not. 

On this specific issue, personally (keeping in mind I'm not a `next` expert), I'd be inclined to not attribute treat files to your top-level page components at all. This would completely avoid the issue. I would aim to have as little treat files in your app as possible, with the goal of more re-usable components/treat files. 

If that's not an option, then I'd probably look to `next` to handle this issue. You could remove the `.js` part of your extension completely (e.g. `index.treat`) which may avoid the `next` issue, but you may run into other issues elsewhere.

**Comment by wyattanderson** [comment]
> On this specific issue, personally (keeping in mind I'm not a next expert), I'd be inclined to not attribute treat files to your top-level page components at all. This would completely avoid the issue. I would aim to have as little treat files in your app as possible, with the goal of more re-usable components/treat files.

Ah, great suggestion! I'll try going down this road as I build the app out.

> You could remove the .js part of your extension completely (e.g. index.treat) which may avoid the next issue, but you may run into other issues elsewhere.

Thought about this, but didn't want to reconfigure my editor, etc. to treat (hah!) the `.treat` extension the same as `.js`.

Thanks!
