### ISSUE TITLE
Gatsby plugin

### ISSUE THREAD

**Issue by deklanw** [seek-oss/treat#51]
Any plans on making a Gatsby plugin?

One exists for Linaria,
https://www.gatsbyjs.org/packages/gatsby-plugin-linaria/

I'm sure many people making Gatsby sites would be interested in zero runtime CSS-in-JS, if they were aware of it

**Comment by mattsjones** [comment]
Funny you ask actually. Originally, we planned on using Gatsby for our docs site and would have set up a plugin at that time. However, Gatsby currently depends on webpack `~4.28.4` whereas treat needs `^4.30.0`. Until Gatsby updates their webpack dependency, treat won't work.

**Comment by deklanw** [comment]
Cool. Thanks for the fast reply.

An official plugin when that gets updated would be great

**Comment by jameslnewell** [comment]
It appears that `gatsby` has updated the version of `webpack` that's used - I currently have `webpack@4.40.2` installed in my project.

I've created a PR for a `gatsby` plugin for `treat` and I'd love some feedback on the PR!

**Comment by graysonhicks** [comment]
@jahredhope Is this PR still outstanding somewhere? Would like to take a look.

**Comment by graysonhicks** [comment]
Nvm, I see it on this repo!

**Comment by mattsjones** [comment]
Resolved by #58

**Comment by mattsjones** [comment]
Seems there is an existing implementation that has the same package name. 

https://github.com/cometkim/gatsby-plugin-treat/issues/1

**Comment by mattsjones** [comment]
This is now all sorted. 👌 

Thanks @cometkim, for giving us the `gatsby-plugin-treat` package name. 😄
