### ISSUE TITLE
Styling & themed examples in docs

### ISSUE THREAD

**Issue by aneeshack4** [seek-oss/treat#52]
Followed documentation on the treat site to try and get the static extraction & theming examples to work using treat but ran into problems.

Here are the steps I went through: 
`npx create-react-app try-treat`

`yarn eject`

edited `webpack.config.js` file to include the TreatPlugin & MiniCssExtractPlugin as follow: (had to comment out the TreatPlugin in isEnvDevelopment because it was throwing a `Failed to compile. tapPromise is not supported on a SyncHook` error otherwise.)
      
    `isEnvDevelopment &&
        new WatchMissingNodeModulesPlugin(paths.appNodeModules),
        // new TreatPlugin({
        //   outputLoaders: [MiniCssExtractPlugin.loader]
        // }),
        new MiniCssExtractPlugin(),
      isEnvProduction &&
        new TreatPlugin({
          outputLoaders: [MiniCssExtractPlugin.loader]
        }),
        new MiniCssExtractPlugin({
          // Options similar to the same options in webpackOptions.output
          // both options are optional
          filename: 'static/css/[name].[contenthash:8].css',
          chunkFilename: 'static/css/[name].[contenthash:8].chunk.css',
        }),`

Did `yarn add --dev babel-plugin-treat@next` and edited `package.json` to have babel plugin as follows:
`"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      "babel-plugin-treat"
    ]
  },`

Made `Button.treat.js` and `Button.js` and imported it in `App.js` to use it. It shows up but it's not getting the style imported from `Button.treat.js`:
![image](https://user-images.githubusercontent.com/4161791/62172331-bb883980-b2e6-11e9-95b2-48e6c7238748.png)
Is there something wrong with how the css is being extracted (as defined in the webpack config) or something wrong with how the button treat style is being using in `Button.js`? 

I followed the docs to try the themed example as well and I'm having problems there using the treat theme - it's breaking on the `useStyles` hook: 
![image](https://user-images.githubusercontent.com/4161791/62172532-58e36d80-b2e7-11e9-98f2-9bcffa24ffbc.png) I didn't change anything besides the name of the const exported to differentiate when I use both the styled and themed examples so I'm not sure what's wrong in the treat usage here - any ideas?

All the code is here: https://github.com/aneeshack4/try-treat3

**Comment by mattsjones** [comment]
Hey 👋,

Thanks for trying out treat. 😄 

The error you're seeing `Failed to compile. tapPromise is not supported on a SyncHook` means you're on an older version of webpack. Update it to anything past `4.30.0`. 

Also, `treat` will defintely not work without the webpack plugin as that's what drives the creation of the styles. 

Hope that resolves your issue.

**Comment by aneeshack4** [comment]
@mattsjones Thanks for the quick response Matt! That got both examples working for me :D
