### ISSUE TITLE
Support inline styles... maybe?

### ISSUE THREAD

**Issue by maraisr** [seek-oss/treat#69]
More aspirational than anything, and do understand the limitations in order to achieve this. But ill mention it none the less.

Please don't get me wrong, I'm fully in support of separation of concerns (within reason, ala React), and thus splitting styles into its own file is great. But _sometimes_ you just want to apply a colour or padding to a div, in a micro component that you really don't want to create a whole treat file for. So I propose the ability to call `style` directly in components, and for a className to be generated right there and then, sue with React, which might mean `useStyles(style())`.

For something like:

```ts
export const NavItem = ({ link, text }) =>
    <a href={link} className={useStyles(style(t => ({ color: t.primaryColour })))}>{text}</a>;
```

Maybe the babel plugin could inject the useStyles, knowing its JSX and detecting React.

**Comment by mattsjones** [comment]
Just to be clear, the separate treat file concept is more to give a distinct boundary to the user (and the bundler) of what is pre-evaluated at build time and what is not. `treat` is optimized for creating computed, highly re-usable CSS. Referencing your example, you probably don't want to create a bunch of the same red color styles, and instead, re-use a single one. 

However, there are definitely cases where inlining styles in the same file would be ideal. In this case, the style function would have to execute at the top level of the file. In your example, the `style` call would have access to the properties of the component, this is a lie though as the style is calculated at build time. I can see this being confusing to users. A single file treat API would have to look more like following. 

```js
const red = style(t => ({ color: t.primaryColour }));

export const NavItem = ({ link, text }) =>
  <a href={link} className={useStyles(red)}>
    {text}
  </a>;
```

Lastly, this isn't trivial to add for support for currently.

**Comment by maraisr** [comment]
Yeah thought it wouldn't be. 🕺 Just thought I'd open up the discussion. We just have a use case for it, in the world of AMP, where including 1 css output at the end, isnt feasible as byte budgets start getting hit. Especially if you encompass an entire design system + application styles into 1 stylesheet. So we thought, amp styles are generally only white-space to an extend, like padding around a heading etc... But not wanting to include the whole css. We were going to just use ignore-loader, and polyfill the treat exports to do _nothing_ in AMP contexts.

**Comment by maraisr** [comment]
Also; just thought i'd ask. If i have 1 treat file, with a class with a siingle red colour property, and another treat file with the same. Doesnt treat optimize this into 1 selector, 1 rule?ie:

```css
._treatFileA_themeA, ._treatFileB_themeB {
   color: red;
}

._treatFileA_themeB, ._treatFileB_themeB {
    color: blue;
}
```

**Comment by mattsjones** [comment]
`treat` doesn't do any class optimization as it could introduce specificity issues. If you automatically re-order the CSS you could make a style be less specific than previously. CSS is actually a huge pain because of this fact. If you could decide what order of importance your styles were at call time (i.e. your className string) than `treat` would look a lot different. This is why facebooks `stylex` has a classnames API.

**Comment by maraisr** [comment]
Sorry.
