### ISSUE TITLE
Intellij users and typescript auto import, not ideal.

### ISSUE THREAD

**Issue by maraisr** [seek-oss/treat#71]
Intellij users have to select types between CommonJS and Module. Because types are deployed twice, without a `types` property set in package.json.

<img width="565" alt="68169655-b9eea180-ffb8-11e9-93e8-3e1f6ad9c856" src="https://user-images.githubusercontent.com/599459/68632240-86bc8d00-0539-11ea-93c5-c41d9230bde3.png">

**Comment by maraisr** [comment]
cc @markdalgleish @michaeltaranto any movement on this issue?

**Comment by mattsjones** [comment]
PR #70 was a reasonable solution to this. Happy to merge that PR, just needed to delete the broken `watch` scripts. Not sure why you closed it?
