### ISSUE TITLE
Assign debug class name by default

### ISSUE THREAD

**Issue by kompot** [seek-oss/treat#75]
Hi,
I think it would be great to have `localDebugName` to be set to exported variable name by default in dev mode.

So that

```
export const rootNoBorder = style({
  borderBottom: 'none',
});
```

would actually become

```
export const rootNoBorder = style({
  borderBottom: 'none',
}, 'rootNoBorder');
```

 but without explicit second parameter.

Is that technically possible?
If yes then maybe there are reasons this is not done this way by default?
Seems just an obvious DX improvement to me.

Thanks!

**Comment by markdalgleish** [comment]
You're in luck—this is already handled by babel-plugin-treat: https://seek-oss.github.io/treat/setup#babel-setup
