### ISSUE TITLE
Serialize treat files for Jest snapshots

### ISSUE THREAD

**Issue by tom-sherman** [seek-oss/treat#78]
Is it possible to serialize treat files for snapshot purposes?

I'm looking to do something similar to https://github.com/thymikee/linaria-jest

Right now I'm using require.context to automatically create a snapshot for each treat file, this works but runs against the compiled code so the snapshot is only testing properties and not the actual style values.

```typescript
test('treat snapshots', () => {
    const context = require.context('.', true, /\.treat\.ts$/);
    context.keys().forEach(key => expect(context(key)).toMatchSnapshot(key));
});
```

```
exports[`treat snapshots: ./Component.treat.ts 1`] = `
Object {
  "base": "base",
  "sizes": Object {
    "lg": "sizes_lg",
    "md": "sizes_md",
    "none": "sizes_none",
    "sm": "sizes_sm",
  },
}
`;
```

**Comment by tom-sherman** [comment]
This actually leads to a more general question of how best to unit test styles.

I have a badge component which applies some `letterSpacing` style if the `value` prop is a string. Right now I have to do this:

```javascript
test('badge has text styles when passed a string', () => {
    const { getByTestId } = renderWithTheme(
        <>
            <Badge value="test" data-testid="string" />
            <Badge value="0" data-testid="stringNum" />
            <Badge value={1} data-testid="num" />
        </>,
    );

    expect(getByTestId('string')).toHaveClass(stylesRef.text);

    expect(getByTestId('stringNum')).toHaveClass(stylesRef.text);

    expect(getByTestId('num')).not.toHaveClass(stylesRef.text);
});
```

Which isn't ideal because the `letterSpacing` could somehow be removed/broken and the test won't fail.

**Comment by mattsjones** [comment]
Hey 👋

Currently, styles are not created when executing treat files outside of webpack (e.g. jest). Theoretically, we could create a runtime version of treat that runs outside of webpack. It would expect to be in a browser style environment like  `jsdom`, so it could inject a `style` tag like runtime based CSS-in-JS libraries do (emotion, styled-components, etc). That way you could assert on the actual styles that are output. 

Outside of the work involved, the main issue I see is it would be a different process of how styles are created and attached. It wouldn't be able to completely assure you that your app is working as expected. For example, the ordering of the CSS could potentially be different.
