### ISSUE TITLE
Watcher is undefined for SSR build

### ISSUE THREAD

**Issue by kompot** [seek-oss/treat#81]
I've encountered that watcher is undefined here
https://github.com/seek-oss/treat/blob/8ee1811fb15d24b5f7591ad687bb8a969aea8623/packages/treat/webpack-plugin/plugin.js#L67
for node environment (SSR with [razzle](https://github.com/jaredpalmer/razzle))

Replacing this code with a solution I found here
https://github.com/s-panferov/awesome-typescript-loader/commit/c7da9ac82d105cdaf9b124ccc4c130648e59168a
makes this code work for both client and server builds

Something like this.

```js
const watcher = watchCompiler.watchFileSystem.watcher || watchCompiler.watchFileSystem.wfs.watcher;
this.treatCompiler.expireCache(
  Object.keys(watcher.mtimes),
);
```

Unfortunately could not find more references on what's the cause of the problem and what's the official way forward.

If you think it's a viable solution I'll be glad to submit a PR.

**Comment by mattsjones** [comment]
Interesting 🤔. What version of webpack is this running on?

Either way, your solution seems reasonable and would be happy to accept a PR 😄

**Comment by kompot** [comment]
I'm on webpack 4.41.5.
Tried some earlier 4.x versions (4.30.0 and 4.23.1) — same results.

Will submit a PR soon.
