### ISSUE TITLE
Composition / Reusing class names across treat files

### ISSUE THREAD

**Issue by danielberndt** [seek-oss/treat#84]
Hello, it's me again!

I'm still very happy with treat and I'm using it more and more in my product.

Here's one thing I'm not really sure about: can I reuse generated classnames across treat files?
An example:

```js
// miniCard.treat.js

export miniCardStyles = {
  base: style({...}),
  byStatus: {
    unassigned: style({color: colors.gray700}),
    assigned: style({color: colors.assigned700}),
    started: style({color: colors.started800}),
    snoozing: style({color: colors.snoozing800}),
    blocked: style({color: colors.blocked800}),
    review: style({color: colors.review800}),
    done: style({color: colors.done800}),
  },
}
```

Coincidentally, the `bigCard.treat.js` uses the same values for `byStatus`. 

So I'd like to do:

```js
// bigCard.treat.js

import {miniCardStyles} from "./miniCard.treat";

export bigCardStyles = {
  base: style({}),
  byStatus: miniCardStyles.byStatus,
}
```

but importing a treat file within a treat file does not seem to be supported (`window not defined`).

Here are two alternatives I see and their drawbacks:

1. create a `tokens.js` file which contains only the raw color information for each status and use e.g. `styleMap` in both `bigCard.treat.js` and `miniCard.treat.js`. 
  **Drawback:** as far as I'm aware, it'll lead to different classNames even though they could be shared
2. apply the two different classes on the component level. I.e. do `<BigCard className={[bigCardStyles.base, miniCardStyles.byStatus[status]].join(" ")}/>`
  **Drawback:** While this approach re-uses class names, I'd like to hide this implementation detail within a treat file. That way the consumer (i.e. the component) doesn't need to care whether it can re-use classNames or not.

Did I maybe miss something? I guess if you say "reusing classnames is a micro optimization that's not worth increasing the API surface for" that's fine with me too! I'm just curious if you have some thoughts here as I couldn't find anything in the docs :)

**Comment by mattsjones** [comment]
Hey Bud 👋 

From a technical perspective each treat file is compiled and executed in isolation so they can't share styles between. 

However, treat is great at creating re-usable utility styles. Our approach is to combine styles together using components and hooks. [Here's an example from our design system](https://github.com/seek-oss/braid-design-system/blob/master/lib/components/Box/useBoxStyles.ts).

The other benefit of this approach is your CSS becomes highly re-usable and you therefore write and ship less of it.

**Comment by maraisr** [comment]
Seeing as all a style* function exposes is a string, theoretically you could:

```ts
// fileA.treat.ts

export const test = style({});

// fileB.treat.ts

import { test } from './fileA.treat';

export const testExtended = style({
    selectors: {
        [`&, ${test}`]: {}
    }
});
```

**Comment by danielberndt** [comment]
Alright, thanks for the clarification. 

As I'm a solo dev on my current project I'm following more of a 80/20 with my design system. I.e. I only formalise styles in my design system components until I'm sure I'll re-use them more often.

This means that for one-offs like nudging an icon into the right position, I'll still fall back to inline styles or emotion's css prop. (thinking about it, I could also start a `one-off.treat.js` to collect these and recognise recurring patterns quicker 🤔)

So it's re-assuring to see that treat's primary purpose is indeed meant utility classes within design systems as this is also the direction I'm slowly but surely heading!
