### ISSUE TITLE
Any chance of support outside of a `.treat.ts` file?

### ISSUE THREAD

**Issue by Tibfib** [seek-oss/treat#86]
First off, I love treat! Thanks for building it!

Instead of:

```javascript
// component.treat.ts
import { style } from 'treat';

export const green = style({
  color: 'green'
});

// component.ts
import { green } from './component.treat.ts';

export function MyComponent() {
  return <div className={green}>This is green</div>;
}

```

It would be awesome to be able to do: 

```javascript
// component.ts
import { style } from 'treat';

const green = style({
  color: 'green'
});

export function MyComponent() {
  return <div className={green}>This is green</div>;
}

```

or even better:

```javascript
// component.ts
import { style } from 'treat';

export function MyComponent() {
  return <div className={style({color: 'green'})}>This is green</div>;
}

```

I've really come to enjoy the `css` prop in emotion and glamor. My ideal (working) solution for CSS is to have a css toolkit library like tailwindcss or basscss (or it could be exported classes from a toolkit treat file) and then to use a prop on the component for everything that falls outside of the toolkit.

Creating an extra file seems like more overhead than is needed for a couple of properties... Using the style prop is fine but sometimes these components are re-used all over the application so it would be nice to abstract it as a class. 

There are other zero-runtime css-in-js libraries that support this type of thing... but they don't have the other upsides of treat (as you talk about in the documentation).

**Comment by lucat1** [comment]
The webpack plugin does support loading from files that don't include the `treat.(js|ts)` prefix. You may wanna try that via this option:
https://github.com/seek-oss/treat/blob/master/packages/treat/webpack-plugin/plugin.js#L35

**Comment by mattsjones** [comment]
Hey 👋,

This feature would be possible but with trade-offs. For example, you would need to declare your styles at the top level of the file. Creating styles within a component render wouldn't work, as all the styles are pre-computed at build time. Also, I think the main benefit of treat is being able to easily generate highly re-usable classes. I wouldn't advise the treat file per component style that was very common with CSS modules. 

However, I understand that sometimes you just need some component specific styles and having a separate file is an unneeded mental overhead. This isn't something we're working on currently but will definitely consider in future.

**Comment by kripod** [comment]
I’m not quite familiar with the architecture of treat, but linaria supports using its `css` tag [without dynamic styles](https://github.com/callstack/linaria/blob/master/README.md#trade-offs). I think that this library could provide similar semantics for its `style` function, suggesting [alternative approaches](https://github.com/callstack/linaria/blob/master/docs/DYNAMIC_STYLES.md) for more dynamism.

The example given below:

```tsx
import { style } from 'treat';

export function MyComponent() {
  return <div className={style({color: 'green'})}>This is green</div>;
}
```

Could be improved further by offering a Babel transform for `css` props on elements, which would extend `className`:

```tsx
export function MyComponent() {
  return <div css={{ color: ‘green’ }}>This is green</div>;
}
```

Linter rules [could warn about undesired side-effects](https://github.com/lukastaegert/eslint-plugin-tree-shaking), enforcing the constraints of the statically extracted `style` function.

**Comment by maraisr** [comment]
This has been [raised before](https://github.com/seek-oss/treat/issues/69)... by me! 

Having worked a lot with the treat arch - fundamentally this isn't possible. Because of how ordering works, theming etc... effectively, every `treat` theme file is evaluated during build to get a static token map - then those tokens are then sent into the `style` functions, and once again, evaluated at build time.

The only way I can see this working, would be for a babel plugin to extract all `style{Map,Tree}` references, and their dependencies, and then eventuated, and injected back into the source file, maybe through parser hooks within Webpack (which I have experimented with), but as the guys are saying, there are a lot of trade offs.

But I think we need to _watch this space_, as solutions like this would likely need to appear in the future.

**Comment by Tibfib** [comment]
> Creating styles within a component render wouldn't work, as all the styles are pre-computed at build time. 

I actually want it to be pre-compiled at build time and still "define" the styles in the render method. It's for making a better DX. Seems silly to create an ENTIRE file just for this one class. I could use the style prop (and maybe that's the right answer), but what if this component is used thousands of time... using a shared class is more efficient than adding style for each component (but, possibly negligible in practice). 

Basically:

```typescript
// code
import { style } from 'treat';

export function MyComponent() {
  return <div className={style({color: 'green'})}>This is green</div>;
}

// build "output"
import { style } from 'treat';

export function MyComponent() {
  return <div className={"_treat_green"}>This is green</div>;
}
```


> Also, I think the main benefit of treat is being able to easily generate highly re-usable classes. I wouldn't advise the treat file per component style that was very common with CSS modules.

I do agree this is an excellent use case for treat. I'm trying to figure out the best way to do one-off* css rules... for reasons stated above.

*one-off meaning being defined in a component once, not necessarily that the css rule is only used once in the dom. There could be multiple instances of the component.

**Comment by Tibfib** [comment]
> This has been [raised before](https://github.com/seek-oss/treat/issues/69)... by me!
> 
> Having worked a lot with the treat arch - fundamentally this isn't possible. Because of how ordering works, theming etc... effectively, every `treat` theme file is evaluated during build to get a static token map - then those tokens are then sent into the `style` functions, and once again, evaluated at build time.
> 
> The only way I can see this working, would be for a babel plugin (acorn parser hook) to extract all `style{,Map,Tree}` references and their dependencies. Then eventuated, and injected back into the source file. Maybe through parser hooks within Webpack (which I have experimented with)... But as the guys are saying, there are a lot of trade offs.
> 
> But I think we need to _watch this space_, as solutions like this would likely need to appear in the future. Especially with the rise of these "single-file" components. Much like how relay or stylex (from what I can see) from Facebook work..

Hmm, this makes sense. So the main issue is with theming? A single css class string couldn't be extracted ahead of time?

**Comment by mattsjones** [comment]
No, the only technical limitation is creating a style that is only known at runtime, theming is not the concern.
e.g.
```js
// This could work
import { style } from 'treat';

export function MyComponent() {
  return <div className={style({color: 'green'})}>This is green</div>;
}
```
```js
// This won't
import { style } from 'treat';

export function MyComponent(props) {
  return <div className={style({color: props.color})}>This is green</div>;
}
```
I am interested in supporting inline styles but am not sure whether to allow use in dynamic contexts (like react render) as it may be confusing for people why some things work and others don't. One way around this, which is the way facebooks stylex seems to work, is to only allow treat style calls at the top level of the file (kinda like imports).

e.g.
```js
// This could work
import { style } from 'treat';

const green = style({color: 'green'});

export function MyComponent() {
  return <div className={green}>This is green</div>;
}
```

I am currently investigating lots of changes to treat which may become treat v2. Moving away from a separate file approach and towards inline styles is one thing I'm considering and I do have a semi-working prototype of this. Once I get a better idea of what will be in the next major version I will post an issue here detailing the proposed changes and hopefully release an alpha/beta version on npm.

**Comment by Tibfib** [comment]
Ah, that makes sense. I want inline treat for static css only. Any conditional logic would be in choosing which class to apply, not within the class definition.

> I am interested in supporting inline styles but am not sure whether to allow use in dynamic contexts (like react render) as it may be confusing for people why some things work and others don't.

That's a fair point. What if it was named something different? Conceptually it's a lot like babel macros/preval. Name ideas: "prevalStyle", "stylePreval", "styleMacro", "staticStyle", "styleStatic".

```typescript
import { staticStyle } from 'treat';

export function MyComponent() {
  return <div className={staticStyle({color: 'green'})}>This is green</div>;
}
```

**Comment by maraisr** [comment]
Got an update for us buddy? @mattsjones

**Comment by mattsjones** [comment]
> Got an update for us buddy? @mattsjones

We've been discussing this issue a lot and while it's probably not what this thread wants to hear, we've decided not to add support for styles outside of treat files. While sometimes less than ideal, having a static module boundary for treat styles is an honest limitation as the styles are truly static. There's also a lot of complexity to add this feature which doesn't really seem worth the trade-off. Other libraries like [linaria](https://github.com/callstack/linaria) also already solve this issue quite nicely, but with different trade-offs. 

Lastly (and maybe most importantly), I think it sends the wrong message about what treat is truly great at — creating utility CSS. If your app has 100s/1000s of treat files then it might not be the right library for your architecture. Runtime CSS-in-JS libraries are excellent choices for a lot of apps, and in most cases will probably have negligible performance cost (or maybe even be faster in some aspects).  

> Also; what are these "lots of changes"?

Changes I'm referring to here are mostly internal changes with how we integrate with webpack and getting webpack 5 compatibility working. Still unsure whether this will impact the public API or not.

**Comment by kripod** [comment]
In the last few days, I've been working on a CSS-in-JS framework called [glaze](https://github.com/kripod/glaze), built upon treat. More details are available [in these tweets](https://twitter.com/kripod97/status/1241524939473248256).

Sneak peeks at the API _(heavily inspired by [Theme UI](https://theme-ui.com/)):_

![image](https://user-images.githubusercontent.com/14854048/77240266-486c6400-6be4-11ea-93e1-587d87d5bb3d.png)

![image](https://user-images.githubusercontent.com/14854048/77240278-68038c80-6be4-11ea-9631-0ee0fc224cef.png)
