### ISSUE TITLE
Guidance on removing unused CSS generated from Treat files?

### ISSUE THREAD

**Issue by tom-sherman** [seek-oss/treat#87]
We are shipping a component library which needs to compile Treat at build time and want to allow consumers to  use a tool like PurgeCSS to remove unused CSS.

We've tried [this guide](https://purgecss.com/css_modules.html) on a consumer level which describes getting PurgeCSS setup with CSS modules - the CSS file either includes all of the Treat CSS or none of it when tweaking the configuration...

Does anyone have any examples or advice about how to get such a setup to work?

**Comment by mattsjones** [comment]
Are the treat files being compiled to CSS separately to the consuming app? As in two separate webpack steps?

**Comment by tom-sherman** [comment]
Finally figured out how to output a CSS file per .treat.ts file, so consumers can import each CSS file - this get's a bit complicated in our setup because we compose our components internally - meaning you could import component `A` but because it uses compnent `B` under the hood, you have to import A.css **and** B.css. I've updated the description to reflect this.

@mattsjones To answer your question, yes. We're building Treat declarations to CSS and the consuming app will import these.

**Comment by mattsjones** [comment]
Right. Not much treat can do if you're doing multiple compiles. I'm assuming compiling your app at the same time as the component library is not an option? That's how we manage our component library/app builds.

**Comment by tom-sherman** [comment]
We ideally didn't want to go down that route but I think it will be serviceable if it's the only option. It's a great help that the webpack plugin is so easy to setup, thanks for your advice!
