### ISSUE TITLE
RuntimeTemplate.moduleId(): Module `*.treat.ts` has no id. This should not happen

### ISSUE THREAD

**Issue by kompot** [seek-oss/treat#91]
Hi,
I've been experiencing really strange errors in webpack builds.

Seems like treat webpack plugin sometimes (?) does not return (?) module ID to webpack upon compilation (if I understand the process correctly). 

The exact error during webpack build is
```
/Users/xxx/projects/yyy/frontm/node_modules/babel-loader/lib/index.js??ref--7-oneOf-2!/Users/xxx/projects/yyy/front/SomeComponent.tsx
RuntimeTemplate.moduleId(): Module /Users/xxx/projects/yyy/frontm/node_modules/treat/webpack-plugin/loader.js??ref--4-0!/Users/xxx/projects/yyy/frontm/node_modules/babel-loader/lib/index.js??ref--7-oneOf-2!/Users/xxx/projects/yyy/front/SomeComponent.treat.ts has no id. This should not happen.
```

Also there is another way of failing: webpack build succeeds but there are some ```__webpack_require__(null)``` and this is null is that missing ID (as there are pre-terser comments and it's that exact module). And in this case I get a runtime error.

But I believe this is basically the same problem.

Unfortunately, I can't create a small reproducible repo as both these errors seem to vanish when I delete some other code and barebones example has no problems. I'll try to accomplish this but can't guarantee.

The most important thing: the very same code outputs different results.
So sometimes I get `__webpack_require__(null)` instead of treat import, rerun the build without changing anything and got correct module id like `__webpack_require__(53)`.

Seems like some race condition.

It also should be noted that this `treat` module I'm talking about is imported into more than 1 React component. I understand it's not the best way to deal with CSS and goes against CSS best practices but I believe that should work ok in terms of compilation.

While I'm trying to come up with a reproducible repo, could you please guide me into the direction where this error might originate from?

**Comment by mattsjones** [comment]
Hey 👋,

Sorry you've hit this issue. I have seen it occur in certain niche situations but haven't got to the bottom of the exact cause. All I know currently, is it tends to only occur when in combination with the [optimization.concatenateModules](https://webpack.js.org/configuration/optimization/#optimizationconcatenatemodules) option. Turning `concatenateModules` off is obviously not an ideal workaround but can fix the issue (at least temporarily). If you do manage to find a way to consistently reproduce it please let me know as it would help tracking down the root cause. 

If disabling `concatenateModules` doesn't work that would also be useful to know.

Also in regards to:

> It also should be noted that this treat module I'm talking about is imported into more than 1 React component. I understand it's not the best way to deal with CSS and goes against CSS best practices but I believe that should work ok in terms of compilation.

I don't see anything wrong with this approach. Treat was designed to make creating re-usable CSS easier. 😄

**Comment by kompot** [comment]
Yep, `concatenateModules` does seem to help, thanks.

Still unable to create a repo detached from commercial code. But will try as `concatenateModules` seems to put some 40kb gzip penalty on our codebase.

**Comment by kompot** [comment]
Here's a minimal repo with a failing compilation (I hope it's stable, tested on 2 machines).
It's basically a create-react-app with < 10 components and a theme provider.

Master branch is failing
https://github.com/kompot/treat-no-module-id

Either of these 2 "fixes" make the build pass
https://github.com/kompot/treat-no-module-id/pull/1/files
https://github.com/kompot/treat-no-module-id/pull/2/files

Would be happy to submit a PR if you have any ideas what should be fixed.

**Comment by mattsjones** [comment]
Thanks for this bud. Will take a look.

**Comment by kompot** [comment]
Also another "fix" makes the problem disappear.
https://github.com/kompot/treat-no-module-id/pull/3
Seems like it might be related to using code splitting.

Have you had any chance to take look?

**Comment by kompot** [comment]
I've actually created a much more simple barebones repo
https://github.com/kompot/treat-no-module-id-2

No typescript, minimal webpack config. Fails the same way. And is fixed with same fixes.
https://github.com/kompot/treat-no-module-id-2/pull/1
https://github.com/kompot/treat-no-module-id-2/pull/2
https://github.com/kompot/treat-no-module-id-2/pull/3

**Comment by kompot** [comment]
Also seems to be fixes in webpack 5 beta/master
https://github.com/webpack/webpack/issues/10409
