### ISSUE TITLE
@font-face declarations

### ISSUE THREAD

**Issue by maraisr** [seek-oss/treat#93]
When you're wanting to define `@font-face` declarations, you'd do this with `globalStyle` if I'm not mistaken. But it seems like `globalStyle`, deep merges all selectors into the last one, something akin to `globalStyles[selector] = style` rather than some push.

My problem:
```ts
import { FontFace } from 'csstype';

globalStyle('@font-face', { fontFamily: 'abc132', fontWeight: 400, src: 'url for 400 weight etc...'} as FontFace);
globalStyle('@font-face', { fontFamily: 'abc132', fontWeight: 500, src: 'url for 500 weight etc...'} as FontFace);
globalStyle('@font-face', { fontFamily: 'abc132', fontWeight: 700, src: 'url for 700 weight etc...'} as FontFace);
```

however, only the `700` is emitted.

I see that braid uses runtime tokens to define link tags for fonts. 

https://github.com/seek-oss/braid-design-system/blob/d2d24813ba2f9158a8c71387da4062fde88115d6/lib/themes/makeBraidTheme.ts#L174-L187

which is great. But we "own" a non public font, so the definitions need to be self hosted, which also mean we have to define the font-face tags.

**Comment by maraisr** [comment]
Upon further investigation, yeah a `Object.assign` takes place, so the "last" one will take precidence.

```ts
 const addLocalCss = styles => {
    localStyles = Object.assign({}, localStyles, styles);
  };
```
> packages/treat/webpack-plugin/loader.js

**Comment by maraisr** [comment]
Can I please get an update regarding this issue please @michaeltaranto @mattsjones @michaeltaranto

**Comment by MadebyAe** [comment]
@maraisr 👋  Did you find any workaround? I am having the same issue.

**Comment by maraisr** [comment]
@MadebyAe not inside Treat no, I believe it's still either Seek folk. Our hacky solution now is to just include the fonts in as a standard css file.

**Comment by MadebyAe** [comment]
Update: I migrated to vanilla extract and is working as expected.
