### ISSUE TITLE
Sharing theme tokens with the runtime

### ISSUE THREAD

**Issue by kripod** [seek-oss/treat#97]
Sometimes, a theme's specific tokens may be required during runtime. E.g. for generating styles with theme-based breakpoints on the fly. I propose the following API for making values of a theme's tokens importable from runtime:

```ts
// Component.treat.ts
import { getTokens } from 'treat';

export const sharedTokens = getTokens(
  // theme => tokens
  ({ breakpoints, shorthands, aliases }) => ({ breakpoints, shorthands, aliases })
);
```

Usage:

```tsx
import { sharedTokens } from './Component.treat';

export default function Component() {
  return <div>{sharedTokens.breakpoints.join()}</div>;
}
```

**Comment by kripod** [comment]
@markdalgleish This would greatly simplify the implementation of [glaze](https://github.com/kripod/glaze). No [`GlazeProvider`/`useRuntimeTheme()`](https://github.com/kripod/glaze/blob/1f7ebfa2266adfb3073a715613b56bba7c2f4d92/packages/glaze/src/GlazeContext.tsx) would be required and alongside #96, Gatsby integration would be a bliss.

**Comment by maraisr** [comment]
Hi @kripod you can crate runtime tokens quite easily. Simply reexport the tokens you've given `createTheme`. I've done something similar here: https://github.com/autoguru-au/overdrive/blob/3bcf649fdb6ea293248cc338b469a51b28823257/lib/themes/makeTheme.ts#L6-L12

**Comment by kripod** [comment]
@maraisr Sounds viable, thanks! I’ve been doing something similar, but was wondering whether creating a custom provider could be avoided.

**Comment by maraisr** [comment]
Yeah! We have a custom provider too! It wraps the ThemeProvider from treat.

**Comment by kripod** [comment]
I'm closing this, as it can be solved by creating a custom theme provider.
